# compose.prod.yaml
# Production environment override
services:
  php:
    build:
      target: frankenphp_prod
    env_file:
      - .env
      - .env.prod
    volumes: !override 
      - ./supervisord:/etc/supervisor
      - ./.env:/app/.env
      - caddy_data:/data
      - caddy_config:/config
      - ./symfony/frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro
      - ./symfony/frankenphp/conf.d/20-app.prod.ini:/usr/local/etc/php/app.conf.d/20-app.prod.ini:ro

  lolsauce-node: !reset null

  lolsauce-phpmyadmin: !reset null

  database: !reset null