services:
  LoLSauce-php:
    image: php:8.4-cli
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./symfony:/var/www/html
    ports:
      - "8080:8000/tcp"
      - "443:443/tcp"
      - "443:443/udp"

  LoLSauce-mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql

  LoLSauce-phpmyadmin: 
    image: phpmyadmin

  LoLSauce-node:
    image: node
    build:
      context: .
      dockerfile: Dockerfile.React
    volumes:
      - ./front:/app
    working_dir: /app
    command: sh -c "npm run dev -- --host"
    ports:
    - "5173:5173"
    stdin_open: true
    tty: true