# compose.prod.yaml
# Production environment override
services:
  php:
    build:
      target: frankenphp_prod
    env_file:
      - .env
      - .env.prod
      
  lolsauce-node:
    build:
      target: react_prod
  
  lolsauce-phpmyadmin:
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"