services:
  LoLSauce-php:
    image: php:8.4-cli
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html:cache
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"

  LoLSauce-mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql

  LoLSauce-phpmyadmin: 
    image: phpmyadmin

  LoLSauce-node:
    image: node