# compose.proxy_override.yaml
services:
  php:
    networks:
      - proxy
    environment:
      - APP_TRUSTED_HOSTS=lolsauce.fr
    ports: !override 
      - 80:${PROXY_PORT:-80}

networks:
  proxy:
    name: ${PROXY_NETWORK_NAME}
    external: true