services:
  LoLSauce-php:
    image: php:8.2-cli
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html:cache
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"

  LoLSauce-mysql:
    image: mysql

  LoLSauce-phpmyadmin: 
    image: phpmyadmin

  LoLSauce-node:
    image: node