FROM php:8.4-cli
#set up the workdir
WORKDIR /app
VOLUME /app/var/
#update and remove useless packages
RUN apt-get update && apt-get install -y --no-install-recommends \
	git \
	&& rm -rf /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer require symfony/maker-bundle --dev
RUN composer require symfony/security-bundle
RUN composer require symfony/webpack-encore-bundle
RUN composer require symfony/serializer-pack