FROM php:8.4-cli
#set up the workdir
WORKDIR /var/www/html/
VOLUME /var/www/html/var/
#update and remove useless packages
RUN apt-get update && apt-get install -y --no-install-recommends \
	git \
    zip \
    unzip \
	&& rm -rf /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

#installation de compose au cas où on a besoin d'executer des commandes
COPY --link ./symfony/ ./
RUN set -eux; \
	composer install --no-cache --prefer-dist --no-dev --no-autoloader --no-scripts --no-progress

RUN composer require symfony/security-bundle
RUN composer require symfony/maker-bundle --dev
RUN composer require symfony/serializer-pack

#installation de symfony
RUN curl -sS https://get.symfony.com/cli/installer | bash
#permet de pouvoir utiliser la commande sans redémarrer le shell
ENV PATH="/root/.symfony5/bin:$PATH"
#permet de créer une nouvelle application si il n'y a rien dans le fichier /var/www/html
CMD ["symfony", "server:start", "--allow-all-ip", "--port=8000"]
RUN symfony server:ca:install