FROM node:20-alpine AS assets_builder

WORKDIR /app
COPY front/package*.json ./
RUN npm install

COPY --link .env ./

COPY front/ ./

RUN npm run build-prod

#syntax=docker/dockerfile:1

# Versions
FROM dunglas/frankenphp:1-php8.4 AS frankenphp_upstream

# The different stages of this Dockerfile are meant to be built into separate images
# https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage
# https://docs.docker.com/compose/compose-file/#target


# Base FrankenPHP image
FROM frankenphp_upstream AS frankenphp_base

WORKDIR /app

VOLUME /app/var/

# persistent / runtime deps
# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends \
	acl \
	file \
	gettext \
	git \
	pigz \
	tar \
	supervisor \
	libgd-dev \
	&& docker-php-ext-install gd\
	&& rm -rf /var/lib/apt/lists/*

COPY --link supervisord/ /etc/supervisor/

RUN set -eux; \
	install-php-extensions \
		@composer \
		apcu \
		intl \
		opcache \
		zip \
	;

# https://getcomposer.org/doc/03-cli.md#composer-allow-superuser
ENV COMPOSER_ALLOW_SUPERUSER=1

ENV PHP_INI_SCAN_DIR=":$PHP_INI_DIR/app.conf.d"

###> recipes ###
###> doctrine/doctrine-bundle ###
RUN install-php-extensions pdo_mysql
###< doctrine/doctrine-bundle ###
###< recipes ###

COPY --link ./symfony/frankenphp/conf.d/10-app.ini $PHP_INI_DIR/app.conf.d/
COPY --link --chmod=755 ./symfony/frankenphp/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
COPY --link ./symfony/frankenphp/Caddyfile /etc/frankenphp/Caddyfile

ENTRYPOINT ["docker-entrypoint"]

HEALTHCHECK --start-period=60s CMD curl -f http://localhost:2019/metrics || exit 1
CMD [ "frankenphp", "run", "--config", "/etc/frankenphp/Caddyfile" ]


# Dev FrankenPHP image
FROM frankenphp_base AS frankenphp_dev

ENV APP_ENV=dev
ENV XDEBUG_MODE=debug,develop,coverage
ENV FRANKENPHP_WORKER_CONFIG=watch
ENV FRANKENPHP_WORKER_COUNT="num 1"
ENV PHP_IDE_CONFIG="serverName=symfony"
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# prevent the reinstallation of vendors at every changes in the source code
RUN set -eux; \
	install-php-extensions \
		xdebug \
	;

COPY --link ./symfony/frankenphp/conf.d/20-app.dev.ini $PHP_INI_DIR/app.conf.d/

CMD [ "frankenphp", "run", "--config", "/etc/frankenphp/Caddyfile", "--watch" ]

# Prod FrankenPHP image
FROM frankenphp_base AS frankenphp_prod

ENV APP_ENV=prod

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

COPY --link ./symfony/frankenphp/conf.d/20-app.prod.ini $PHP_INI_DIR/app.conf.d/

# prevent the reinstallation of vendors at every changes in the source code
COPY --link ./symfony/composer.* ./symfony/symfony.* ./
RUN set -eux; \
	composer install --no-cache --prefer-dist --no-dev --no-scripts --no-progress

# add the compiled frontend
COPY --link --from=assets_builder /app/dist public/build

COPY --link .env ./

COPY --link symfony/ ./

RUN set -eux; \
	mkdir -p var/cache var/log; \
	composer dump-autoload --classmap-authoritative --no-dev; \
	composer dump-env prod; \
	composer run-script --no-dev post-install-cmd; \
	chmod +x bin/console; sync;
