apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - php-deployment.yaml
  - database-stateful-set.yaml
  - php-ingress.yaml

configMapGenerator:
  - name: env-config
    envs:
      - .env
